import{a as w,S as b,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const S="50818292-28c953def5feac0614fc2706b",v="https://pixabay.com/api/";async function u(s,t=1){const o=new URLSearchParams({key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}),{data:i}=await w.get(`${v}?${o}`);return i}const f=document.querySelector(".gallery"),p=document.querySelector(".load-more-btn"),h=document.querySelector(".loader"),R=new b(".gallery a",{captionsData:"alt",captionDelay:250});function m(s){const t=s.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
               <ul class="info">
<li class="photo-info">👍 <span class="span">${o.likes}</span></li>
<li class="photo-info">👁 <span class="span">${o.views}</span></li>
<li class="photo-info">💬 <span class="span">${o.comments}</span></li>
<li class="photo-info">⬇️ <span class="span">${o.downloads}</span></li>
</ul>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){f.innerHTML=""}function g(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function q(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}const E=document.querySelector(".form"),B=document.querySelector(".load-more-btn");let l="",n=1,d=0;E.addEventListener("submit",async s=>{if(s.preventDefault(),l=s.currentTarget.elements["search-text"].value.trim(),!l)return a.warning({title:"Warning",message:"Enter a search term",position:"topRight"});n=1,$(),L(),g();try{const t=await u(l,n);if(d=t.totalHits,t.hits.length===0){a.error({title:"Error",message:"No images found",position:"topRight"});return}m(t.hits),n*15<d&&q()}catch{a.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{y()}});B.addEventListener("click",async()=>{n+=1,g();try{const s=await u(l,n);m(s.hits);const{height:t}=document.querySelector(".gallery .gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),n*15>=d&&(L(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
